# Use an official Node.js runtime as a parent image
FROM node:14

# Set the working directory in the container
WORKDIR /app

# Copy package.json and package-lock.json
COPY frontend/package*.json ./

# Install any needed packages specified in package.json
RUN npm install

# Copy the rest of your application code
COPY frontend/ .

# Build the React app
RUN npm run build

# Make port 3000 available to the world outside this container
EXPOSE 3000

# Start the React app
CMD ["npm", "start"]
